---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: anal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anal
  template:
    metadata:
      labels:
        app: anal
    spec:
      containers:
        - name: anal-app
          image: yetiatdocker/anal-app:latest
          envFrom:
            - configMapRef:
                name: config

---

apiVersion: v1
kind: Service
metadata:
  name: anal-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: auth

---
