apiVersion: apps/v1
kind: Deployment
metadata:
  name: anal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anal
  template:
    metadata:
      labels:
        app: anal
    spec:
      containers:
        - name: anal-app
          image: yetiatdocker/anal-app:latest
          env:
          - name: DB_NAME 
            value: "docker"
          - name: DB_USER 
            value: "docker"
          - name: DB_PASSWORD 
            value: Password
          - name: MONGO_NAME 
            value: "root"
          - name: MONGO_PASS 
            value: "Password"
          - name: MONGO_DB_NAME
            value: "docker"