apiVersion: apps/v1
kind: Deployment
metadata:
  name: acit3495
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acit3495
  template:
    metadata:
      labels:
        app: acit3495
    spec:
      containers:
        - name: anal-app
          image: yetiatdocker/anal-app
        - name: auth-app
          image: yetiatdocker/auth-app
        - name: node-app
          image: yetiatdocker/node-app
        - name: results-app
          image: yetiatdocker/results-app
        # - name: acit3495
        - name: mongodbserver
          image: mongo:6.0
          volumeMounts:
          - name: volume
            mountPath: /etc/volume
        # - name: acit3495
        - name: mysqlserver
          image: mysql:8.0
          volumeMounts:
          - name: volume
            mountPath: /etc/volume
          # envFrom:
          #   - secretRef:
          #     name: app-secret
          # volumeMounts:    
          #   - mountPath: /var/lib/mysql    
          #     name: mysql-volume
      volumes:
        - name: volume
          secret:
            secretName: app-secret
            optional: false
