apiVersion: apps/v1
kind: Deployment
metadata:
  name: ACIT3495-App
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ACIT3495-App
  template:
    metadata:
      labels:
        app: ACIT3495-App
    spec:
      containers:
        - name: mongodb_server
          image: mongo:6.0
          envFrom:
            - secretRef:
              name: app-secret
        - name: mysql_server
          image: mysql:8.0
          envFrom:
            - secretRef:
              name: app-secret
