apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
    # DB_HOST: mysql_server
    # DB_USER: docker
    # DB_PASSWORD: Password
    # DB_NAME: docker
    # DB_PORT: 3306
    # MYSQLDB_ROOT_PASSWORD: Password
    # MONGO_NAME: root
    # MONGO_PASS: Password


