apiVersion: apps/v1
kind: Deployment
metadata:
  name: acit3495
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acit3495
  template:
    metadata:
      labels:
        app: acit3495
    spec:
      containers:
        - name: auth-app
          image: yetiatdocker/auth-app:latest
          ports:
            - containerPort: 5000

        - name: node-app
          image: yetiatdocker/node-app:latest
          env:
          - name: DB_HOST
            value: "mysqlserver"
          - name: DB_USER 
            value: "docker"
          - name: DB_PASSWORD 
            value: Password
          - name: DB_NAME 
            value: "docker"
          ports:
            - containerPort: 3000

        - name: anal-app
          image: yetiatdocker/anal-app:latest
          env:
          - name: DB_HOST
            value: "mysqlserver"
          - name: DB_NAME 
            value: "docker"
          - name: DB_USER 
            value: "docker"
          - name: DB_PASSWORD 
            value: Password
          - name: MONGO_NAME 
            value: "root"
          - name: MONGO_PASS 
            value: "Password"
          - name: MONGO_DB_HOST
            value: "mongodbserver"
          - name: MONGO_DB_NAME
            value: "docker"

        - name: results-app
          image: yetiatdocker/results-app:latest
          env:
          - name: UNAME 
            value: "root"
          - name: PASSWD 
            value: "Password"
          ports:
            - containerPort: 5001

        # - name: mongodbserver
        #   image: mongo:6.0
        #   env:
        #   - name: MONGO_NAME 
        #     value: "root"
        #   - name: MONGO_PASS 
        #     value: "Password"
        #   ports:
        #     - containerPort: 27017

        # - name: mysqlserver
        #   image: mysql:8.0
        #   env:
        #   - name: MYSQL_DATABASE
        #     value: "docker"
        #   - name: MYSQL_USER 
        #     value: "docker"
        #   - name: MYSQL_PASSWORD 
        #     value: "Password"
        #   - name: MYSQL_ROOT_PASSWORD 
        #     value: "Password"
        #   ports:
        #     - containerPort: 3306

      # volumes:
      #   - name: secret
      #     secret:
      #       secretName: app-secret
      #       optional: false
