apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  MYSQL_ROOT_PASSWORD: Password
  MYSQL_DATABASE: docker
  MYSQL_USER: docker
  MYSQL_PASSWORD: Password
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: Password
  MONGO_INIT_DB_NAME: docker
  DB_NAME: docker
  DB_USER: docker
  DB_PASSWORD: Password
  MONGO_NAME: root
  MONGO_PASS: Password
  MONGO_DB_NAME: docker
  UNAME: root
  PASSWD: Password
  MONGO_HOST: mongo-service
  MYSQL_HOST: mysql-service