apiVersion: v1
kind: Service
metadata:
  name: external-lb
spec:
  type: LoadBalancer
  ports:
  - name: results
    port: 5001
    targetPort: 5001
  - name: auth
    port: 5000
    targetPort: 5000
  # - name: node
  #   port: 3000
  #   targetPort: 3000
  selector:
    lbtype: external