---

apiVersion: v1
kind: Service
metadata:
  name: external-lb
spec:
  type: LoadBalancer
  ports:
  - name: auth
    port: 5000
    targetPort: "5000-port"
  - name: node
    port: 3000
    targetPort: "3000-port"
  - name: results
    port: 5001
    targetPort: "5001-port"
  selector:
    lbtype: external

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        app: auth
        lbtype: external
    spec:
      containers:
        - name: auth-app
          image: jovan9876/auth-app:latest
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 5000
              name: "5000-port"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: node
    spec:
      containers:
        - name: node-app
          image: jovan9876/node-app:latest
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 3000
              name: "3000-port"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      hostname: mysqlserver
      containers:
        - name: mysqlserver
          image: mysql:8.0
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 3306


---

apiVersion: v1
kind: Service
metadata:
 name: mysql-service
spec:
 selector:
   app: mysql
 ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: anal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anal
  template:
    metadata:
      labels:
        app: anal
    spec:
      containers:
        - name: anal-app
          image: jovan9876/anal-app:latest
          envFrom:
            - configMapRef:
                name: config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      hostname: mongodbserver
      containers:
        - name: mongodbserver
          image: mongo:6.0
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
 name: mongo-service
spec:
 selector:
   app: mongo
 ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: results
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: results
    spec:
      containers:
        - name: results-app
          image: jovan9876/results-app:latest
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 5001
              name: "5001-port"

---