---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-app
          image: yetiatdocker/node-app:latest
          envFrom:
            - configMapRef:
                name: config
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: node-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: node

---

apiVersion: v1
kind: Service
metadata:
 name: node-service
spec:
 selector:
   app: node
 ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000

---
