apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      hostname: mongodbserver
      containers:
        - name: mongodbserver
          image: mongo:6.0
          envFrom:
            - configMapRef:
                name: config

          ports:
            - containerPort: 27017
