---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      hostname: mongodbserver
      containers:
        - name: mongodbserver
          image: mongo:6.0
          envFrom:
            - configMapRef:
                name: config

          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo

---

apiVersion: v1
kind: Service
metadata:
 name: mongo-service
spec:
 selector:
   app: mongo
 ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017

---
